### ISSUE TITLE
create circleci build

### ISSUE THREAD

**Issue by mattberther** [cds-hooks/cds-validator#1]
@jmandel as part of the transfer i want to get the circleci build going again. however, im not a repo admin for cds-validator. can you set that permission so I can configure the ci build?

thanks!

**Comment by jmandel** [comment]
You should be set as admin now!

**Comment by mattberther** [comment]
Thanks @jmandel. One other piece seems to be missing. circleci doesnt seem to be allowed for the cds-hooks organization. Can you set that up?

Sorry about the hassle.

**Comment by jmandel** [comment]
No hassle -- I was confused by the permission request because it talked
about access to "private data". And our repos don't contain private data,
so I thought the access wouldn't be required. Will fix.

**Comment by jmandel** [comment]
Should be set now!

**Comment by mattberther** [comment]
You are a star. Thanks! Appears to be resolved and building.
